name: Update README and Our-Journey Page

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  update-readme-and-team:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        run: python update_readme.py

      - name: Check for changes
        run: git status

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md assets/html/our-journey.html
          git commit -m "Update README.md and our-journey.html with latest data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
