name: Update Drive Hierarchy JSON Backup Copy

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  update-drive-hierarchy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        env:
          DRIVE_HIERARCHY_BACKUP_COPY: ${{ secrets.DRIVE_HIERARCHY_BACKUP_COPY }}
        run: python _scripts/update_drive_hierarchy_backup_copy.py

      - name: Check for changes
        run: git status

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ./assets/html/drive_hierarchy_backup_copy.json
          git commit -m "Update drive_hierarchy_backup_copy.json with latest data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
