name: User Upload Count

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run script
        env:
          UPLOADER_FILE_COUNT: ${{ secrets.UPLOADER_FILE_COUNT }}
          UPLOADER_EMAILS: ${{ secrets.UPLOADER_EMAILS }}
        run: python user_upload_summary.py

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add ./assets/html/total_user_file_counts.json || true
          git diff --cached --quiet || git commit -m "Update total_user_file_counts.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
